config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :posts, only: [:new, :create, :destroy]
    resources :categories
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      collection do
        get :archived
      end

      member do
        patch :archive
        patch :unarchive
        patch :nullify_posts
        patch :nullify_roles
      end
    end
  end

  devise_for :users

  root "posts#index"

  resources :posts, only: [:index, :show, :edit, :update] do
    collection do
       get :published
       get :draft
       get :recent
       get :search
    end

    member do
       patch :publish
       patch :unpublish

       post :watch
     end
  end

  resources :categories, only: [:show]

  resources :posts, only: [] do
    resources :reviews, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  skip_after_action :verify_authorized, :verify_policy_scoped
  
  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  after_action :verify_authorized, except: [:index, :published, :draft, :recent, :search],
    unless: :devise_controller?
  after_action :verify_policy_scoped, only: [:index],
    unless: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    redirect_to root_path, alert: "You aren't allowed to do that."
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
  def roles
    hash = {}

    Role.available_roles.each do |role|
      hash[role.titleize] = role
    end

    hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
      unless parts.empty?
        content_for :title do
          (parts << "News City").join(" - ")
        end
      end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/views/admin/application/index.html.slim
.row#admin
  .col-md-9
    .header
      h1
        | Admin Lounge
      p
        | Welcome to News City Admin Lounge. Please enjoy your stay.

  .col-md-3
    h2
      | Admin Links
    ul.nav.nav-stacked
      li
        = link_to "Users", admin_users_path, class: "users"

      li.dropdown.categories-admin
        a.dropdown-toggle.categories data-toggle="dropdown" href="#"
          | Categories admin
          span.caret
        ul.dropdown-menu role="menu"
          li class=(current_page?("/admin/categories") ? 'active' : '')
            = link_to "List all by order", admin_categories_path
          li.divider
          - Category.all.each do |category|
            li class=(current_page?("/admin/categories/#{category.id}") ? 'active' : '')
              = link_to category.name, admin_category_path(category)

      li
        = link_to "States", admin_states_path, class: "states"