config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :posts, only: [:new, :create, :destroy]
    resources :categories
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      collection do
        get :archived
      end

      member do
        patch :archive
        patch :unarchive
        patch :nullify_posts
        patch :nullify_roles
      end
    end
  end

  devise_for :users

  root "posts#index"

  resources :posts, only: [:index, :show, :edit, :update] do
    collection do
       get :published
       get :draft
       get :recent
       get :search
    end

    member do
       patch :publish
       patch :unpublish

       post :watch
     end
  end

  resources :categories, only: [:show]

  resources :posts, only: [] do
    resources :reviews, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_create :assign_default_state

  belongs_to :author, class_name: "User", :foreign_key => 'author_id'
  belongs_to :state

  has_many :roles, dependent: :delete_all
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :tags, uniq: true
  has_and_belongs_to_many :watchers, join_table: "post_watchers", class_name: "User", uniq: true

  mount_base64_uploader :attachment, AttachmentUploader

  attr_accessor :tag_names

  validates :title,
              presence: true,
              length: { minimum: 10, maximum: 100 },
              uniqueness: true
  validates :subtitle,
              length: { maximum: 100 }
  validates :content,
              presence: true,
              length: { minimum: 30 }
  validates :attachment, file_size: { less_than: 1.megabytes }

  # default_scope              { order('created_at DESC') }
  scope :order_created,   -> { order('created_at DESC') }
  scope :order_published, -> { order('published_at DESC') }
  scope :published,       -> { where("published_at IS NOT NULL").order_published }
  scope :draft,           -> { where("published_at IS NULL").order_created }
  scope :recent,          -> { published.where("published_at > ?", 1.week.ago.to_date) }
  scope :where_title,     ->(term) { where("title LIKE ?", "%#{term}%") }
  scope :where_tag,       ->(term) { select('posts.id, posts.title').joins(:tags).where('tags.name == ?', "#{term}") }


  after_create :author_watches_me

  # def self.draft
  #   where("posts.published_at IS NULL")
  # end

  def published
    if self.published_at?
      " #{self.published_at.strftime('%a %d %b %Y')} at #{self.published_at.strftime('%I:%M:%S %p')}"
    else
      "not yet!"
    end
  end

  def long_title
    "#{title} - #{published_at}"
  end

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end

  def publish
    self.update(published_at: Time.zone.now)
  end

  def unpublish
    self.update(published_at: nil)
  end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      self.tags << Tag.find_or_initialize_by(name: name)
    end
  end

  private

    def assign_default_state
      self.state ||= State.default
    end

    def author_watches_me
      if author.present? && !self.watchers.include?(author)
        self.watchers << author
      end
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_categories, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      flash[:notice] = "Post has been created."
      redirect_to @post
    else
      flash[:alert] = "Post has not been created."
      render "new"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:notice] = "Post has been deleted."
    redirect_to posts_path
  end

  private

  def set_categories
    @categories = Category.all.select(:id, :name)
  end

  def post_params
    params.require(:post).permit(:title,
                                 :subtitle,
                                 :content,
                                 :tag_names,
                                 :attachment,
                                 :attachment_cache,
                                 :remove_attachment,
                                 :remote_attachment_url,
                                 :published_at,
                                 category_ids:[]
                                 )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :publish, :unpublish, :watch]
  before_action :set_categories, only: [:edit, :update]

  def index
    @posts = policy_scope(Post).order('created_at DESC')
  end

  def show
    authorize @post, :show?
    @review = @post.reviews.build(state_id: @post.state_id)
  end

  def edit
    authorize @post, :update?
  end

  def update
    authorize @post, :update?
    @post.author = current_user

    if @post.update(sanitized_parameters)
      flash[:notice] = "Post has been updated."
      redirect_to @post
    else
      flash.now[:alert] = "Post has not been updated."
      render "edit"
    end
  end

  def publish
     authorize @post, :publish?
     @post.publish
     flash[:notice] =  'Post was successfully published.'
     redirect_to @post
  end

  def unpublish
     authorize @post, :unpublish?
     @post.unpublish
     flash[:notice] =  'Post was successfully unpublished.'
     redirect_to @post
  end

  def published
    @posts = policy_scope(Post.published)
    render action: :index
  end

  def draft
    @posts = policy_scope(Post.draft)
    render action: :index
  end

  def recent
    @posts = policy_scope(Post.recent)
    render action: :index
  end

  def search
    #authorize @post, :search?
    if params[:search].present?
      @posts = policy_scope(Post.where_title(params[:search]))
      # @posts = @posts.search(params[:search])
    else
      @posts
    end
    render action: :index
  end

  def watch
    authorize @post, :show?
    if @post.watchers.exists?(current_user.id)
      @post.watchers.destroy(current_user)
      flash[:notice] = "You are no longer watching this post."
    else
      @post.watchers << current_user
      flash[:notice] = "You are now watching this post."
    end

    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The post you were looking for could not be found."
    redirect_to posts_path
  end

  def set_categories
    @categories = Category.all.select(:id, :name)
  end

  def post_params
    params.require(:post).permit(:title,
                                 :subtitle,
                                 :content,
                                 :tag_names,
                                 :attachment,
                                 :attachment_cache,
                                 :remove_attachment,
                                 :remote_attachment_url,
                                 category_ids:[])
  end

  def sanitized_parameters
    whitelisted_params = post_params

    unless policy(@post).change_category?
      whitelisted_params.delete(category_ids:[])
    end

    unless policy(@post).tag?
      whitelisted_params.delete(:tag_names)
    end

    whitelisted_params
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def state_transition_for(review)
    if review.previous_state != review.state
      content_tag(:p) do
        value = "<strong><i class='fa fa-gear'></i> state changed</strong>"
        if review.previous_state.present?
          value += " from #{render review.previous_state}"
        end
        value += " to #{render review.state}"
        value.html_safe
      end
    end
  end

  def toggle_watching_button(post)
    text = if post.watchers.include?(current_user)
      "Unwatch"
    else
      "Watch"
    end
    link_to text, watch_post_path(post),
      class: text.parameterize, method: :post
  end
end

app/views/posts/_form.html.slim
= simple_form_for(post, :html => { :multipart => true }) do |f|
  == render "shared/post_form", f: f, post: post

app/views/posts/edit.html.slim
= title("Edit Post", @post.title)

.header
  h1 Edit Post

== render "form", post: @post

app/views/posts/index.html.slim
= title("Posts")
.header
  h1 Posts
  - unless @posts == nil
    - if policy(@posts).index?
      ul.actions
        li
          = link_to "Published", published_posts_path, class: "published"

        li
          = link_to "Draft", draft_posts_path, class: "draft"

        li
          = link_to "Recent", recent_posts_path, class: "recent"

        - admins_only do
            li
              = link_to "New Post", new_admin_post_path, class: "new"
        end
.header
  br
  ul.actions.search
    li
      = form_tag search_posts_path(@post), method: :get, class: "form-inline" do
        = label_tag "search", "Search", class: "sr-only"
        = text_field_tag "search", params[:search], class: "form-control"
        = submit_tag "Search", class: "btn btn-default"

- if @posts.present?
  #posts
    .container-fluid.text-center.bg-grey
      .row
        - @posts.each do |post|
          .col-sm-4
            = link_to image_tag(post.attachment.small_thumb.url, alt: 'Image', class: "img-responsive img-rounded center-block"), post if post.attachment?
            == render post.state if post.state && !post.published_at?
            h2 = link_to post.title, post
            p = link_to post.subtitle, post

app/views/posts/show.html.slim
= title("Post", @post.title)

#post
  .header
    br
    ul.actions
      - if policy(@post).update?
        = link_to "Edit Post", edit_post_path(@post),
                               class: "edit"
      - admins_only do
        = link_to "Delete Post", admin_post_path(@post),
                                  method: :delete,
                                  data: { confirm: "Are you sure you want to delete this post?" },
                                  class: "delete"
      - if policy(@post).publish?
        - if @post.published_at?
          = link_to "Unpublish", unpublish_post_path(@post), method: :patch, data: { confirm: 'Are you sure you want to unpublish this post?' }, class: "unpublish"
        - else
          = link_to "Publish", publish_post_path(@post), method: :patch, data: { confirm: 'Are you sure you want to publish this post?' }, class: "publish"

  - if policy(@post).show?
    table#attributes.breadcrumb
      - if @post.categories.present?
        tr.categories
          th Categories:
          td
            ul
              == render @post.categories

      - if @post.author.present?
        tr.author
          th Author:
          td = " #{@post.author.email}"

      tr.created_at
        th Created:
        td
          = " #{time_ago_in_words(@post.created_at)} ago"

      - if @post.state.present?
        tr.estado
          th State:
          td
            == render @post.state

      - if @post.tags.any?
        tr#tags
          th Tags:
          td
            == render @post.tags, post: @post

      tr.published
        th Published:
        td
          = " #{@post.published}"

      tr#watchers
        th Watchers:
        td
          = toggle_watching_button(@post)
          br
          = @post.watchers.map(&:email).to_sentence

  .text-center
    h1
      = @post.title
    h1
      small.lead
        = @post.subtitle

    - if @post.attachment.present?
      .attachment
        p
          = image_tag(@post.attachment.thumb.url, alt: 'Image', class: "img-responsive img-thumbnail")
    p.text-justify
      = simple_format @post.content
hr

#reviews
  - if policy(@review).create?
    == render "reviews/form", post: @post, review: @review


    h3.header
      = t(:available_reviews, count: @post.reviews.count)

    - if @post.reviews.persisted.any?
      == render @post.reviews.persisted
    - else
      p There are no reviews for this post.