config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :posts, only: [:new, :create, :destroy]
    resources :categories
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      collection do
        get :archived
      end

      member do
        patch :archive
        patch :unarchive
        patch :nullify_posts
        patch :nullify_roles
      end
    end
  end

  devise_for :users

  root "posts#index"

  resources :posts, only: [:index, :show, :edit, :update] do
    collection do
       get :published
       get :draft
       get :recent
       get :search
    end

    member do
       patch :publish
       patch :unpublish

       post :watch
     end
  end

  resources :categories, only: [:show]

  resources :posts, only: [] do
    resources :reviews, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :roles
  has_many :posts, :foreign_key => 'author_id',
                   :dependent => :nullify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :excluding_archived, -> { where(archived_at: nil) }
  scope :archived,           -> { where("archived_at IS NOT NULL") }


  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def unarchive
    self.update(archived_at: nil)
  end

  def nullify_posts
    self.posts.clear
  end

  def nullify_roles
    self.roles.clear
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end

  def role_on(post)
    roles.find_by(post_id: post).try(:role)
  end

  def has_roles?
    if self.admin?
      true
    elsif self.roles.exists?
      true
    else
      false
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_posts, only: [:new, :create, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :archive, :unarchive, :nullify_posts, :nullify_roles]

  def index
    @users = User.excluding_archived.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    build_roles_for(@user)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    User.transaction do
      @user.roles.clear
      build_roles_for(@user)

      if @user.update(user_params)
        flash[:notice] = "User has been updated."
        redirect_to admin_users_path
      else
        flash.now[:alert] = "User has not been updated."
        render "edit"
        raise ActiveRecord::Rollback
      end
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!"
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end

    redirect_to archived_admin_users_url
  end

  def unarchive
    @user.unarchive
    flash[:notice] = "User has been unarchived."
    redirect_to admin_users_path
  end

  def archived
    @users = User.archived
    render action: :index
  end

  def nullify_posts
    if @user.archived_at?
      if @user.posts.exists?
        @user.nullify_posts
        flash[:warning] = "The user #{@user} has been nullified the posts as author."
      else
        flash[:notice] = "The user #{@user} has not posts as author to be nullified."
      end
    else
      flash[:notice] = "Can't be nullify the posts of the user #{@user}, because it isn't an archived user."
    end

    redirect_to admin_user_path(@user)
  end

  def nullify_roles
    if @user.archived_at?
      if @user.roles.exists?
        @user.nullify_roles
        flash[:warning] = "The user #{@user} has been nullified the roles in posts who was member."
      else
        flash[:notice] = "The user #{@user} has no roles on posts to be nullified."
      end
    else
      flash[:notice] = "Can't be nullify the posts of the user #{@user}, because it isn't an archived user."
    end

    redirect_to admin_user_path(@user)
  end

  private

  def set_posts
    @posts = Post.order(created_at: :desc)
  end

  def build_roles_for(user)
    role_data = params.fetch(:roles, [])
    role_data.each do |post_id, role_name|
      if role_name.present?
        user.roles.build(post_id: post_id, role: role_name)
      end
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, user] do |f|
  = f.input :email
  = f.input :password
  = f.input :admin, label: "Is an admin?"

  h3.header
    | Roles

  table.roles
    - posts.each do |post|
      tr
        th
          = label_tag dom_id(post), post.title, class: "small"
        td
          = select_tag dom_id(post), options_for_select(roles, user.role_on(post)),
                                            name: "roles[#{post.id}]",
                                            include_blank: true

  = f.button :submit, class: "btn btn-primary"

app/views/admin/users/edit.html.slim
h1.header
  | Edit User

== render "form", user: @user, posts: @posts

app/views/admin/users/index.html.slim
h1.header
  - if current_page?('/admin/users/archived')
    | Archived users
  - if current_page?('/admin/users')
    | Users
  ul.actions
    li
      = link_to "New User", new_admin_user_path, class: "new"
    - if current_page?('/admin/users')
      li
        = link_to "Archived users", archived_admin_users_path, class: "archived"
    - if current_page?('/admin/users/archived')
      li
      = link_to "Users", admin_users_path, class: "users"
ul
  - @users.each do |user|
    li
      = link_to user, [:admin, user]

app/views/admin/users/new.html.slim
h1.header
  | New User
  
  == render "form", user: @user, posts: @posts

app/views/admin/users/show.html.slim
h3.header
  - if @user.archived_at?
    | Archived user: <small> #{@user} </small>
  - else
    | User: <small> #{@user} </small>
  ul.actions
    - if @user.archived_at?
      li
        = link_to "Unarchive User", [:unarchive, :admin, @user], method: :patch, data: { confirm: "Are you sure you want to unarchive the user #{@user}?" }, class: "unarchive"
    - else
      li
        = link_to "Edit User", [:edit, :admin, @user], class: "edit"
      li
        = link_to "Archive User",  [:archive, :admin, @user],
                                     method: :patch,
                                     data: { confirm: "Are you sure want to archive this user?" },
                                     class: "delete"
    li
      = link_to "Users", admin_users_path, class: "users"

h4.roles
  | Roles:
  - if @user.roles.any?
    ul.small
      - @user.roles.each do |role|
        li
          = "#{role.post.title}: #{role.role.titleize}"
    - if @user.archived_at?
      = link_to "Nullify Roles", [:nullify_roles, :admin, @user], method: :patch, data: { confirm: "Are you sure want to nullify the roles on postsof the #{@user}?" }, class: "nullify"
  - else
    p.small
      | This user has no roles.

h3.posts
  | Posts as author:
  - if @user.posts.exists?
    ul.small
      - @user.posts.each do |post|
        li
          = "#{post.title}"
    - if @user.archived_at?
      = link_to "Nullify Posts", [:nullify_posts, :admin, @user], method: :patch, data: { confirm: "Are you sure want to nullify the posts as author of the #{@user}?" }, class: "nullify"
  - else
    p.small
      | This user has no posts.