config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'

    resources :posts, only: [:new, :create, :destroy]
    resources :categories
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end

    resources :users do
      collection do
        get :archived
      end

      member do
        patch :archive
        patch :unarchive
        patch :nullify_posts
        patch :nullify_roles
      end
    end
  end

  devise_for :users

  root "posts#index"

  resources :posts, only: [:index, :show, :edit, :update] do
    collection do
       get :published
       get :draft
       get :recent
       get :search
    end

    member do
       patch :publish
       patch :unpublish

       post :watch
     end
  end

  resources :categories, only: [:show]

  resources :posts, only: [] do
    resources :reviews, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base

  def self.default
    find_by(default: true)
  end
  
  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end

  def to_s
    name
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash.now[:alert] = "State has not been created."
      render "new"
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!

    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_path
  end

  private

    def state_params
      params.require(:state).permit(:name, :color)
    end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.slim
= simple_form_for [:admin, state] do |f|
  = f.input :name
  = f.input :color

  = f.submit class: "btn btn-primary"

app/views/admin/states/index.html.slim
.header
  h1 States

  ul.actions
    li
      = link_to "New State", new_admin_state_path, class: "new"

ol#states
  - @states.each do |state|
    li
      == render "states/state", state: state
      - if state.default?
        | (Default)
      - else
        = link_to "Make Default", make_default_admin_state_path(state)

app/views/admin/states/new.html.slim
.header
  h1 New State

== render "form", state: @state